function qdd = Forward_dynamics(k,m,theta1,theta2)
%Forward_dynamics
%    QDD = Forward_dynamics(K,M,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    30-Jul-2025 11:11:05

qdd = [-(k.*theta1-k.*theta2)./m;(k.*theta1-k.*theta2)./m];
end
