function qdd = Forward_dynamics_no_lin(k,l,l0,m,theta1,theta2)
%Forward_dynamics_no_lin
%    QDD = Forward_dynamics_no_lin(K,L,L0,M,THETA1,THETA2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    30-Jul-2025 11:02:31

mt1 = [-(k.*(l0-sqrt(l.^2.*cos(theta1).^2+l.^2.*cos(theta2).^2+l.^2.*sin(theta1).^2+l.^2.*sin(theta2).^2+l0.^2-l.*l0.*sin(theta1).*2.0+l.*l0.*sin(theta2).*2.0-l.^2.*cos(theta1).*cos(theta2).*2.0-l.^2.*sin(theta1).*sin(theta2).*2.0)).*(l0.*cos(theta1)+l.*cos(theta1).*sin(theta2)-l.*cos(theta2).*sin(theta1)).*1.0./sqrt(l.^2.*cos(theta1).^2+l.^2.*cos(theta2).^2+l.^2.*sin(theta1).^2+l.^2.*sin(theta2).^2+l0.^2-l.*l0.*sin(theta1).*2.0+l.*l0.*sin(theta2).*2.0-l.^2.*cos(theta1).*cos(theta2).*2.0-l.^2.*sin(theta1).*sin(theta2).*2.0))./(l.*m)];
mt2 = [(k.*(l0-sqrt(l.^2.*cos(theta1).^2+l.^2.*cos(theta2).^2+l.^2.*sin(theta1).^2+l.^2.*sin(theta2).^2+l0.^2-l.*l0.*sin(theta1).*2.0+l.*l0.*sin(theta2).*2.0-l.^2.*cos(theta1).*cos(theta2).*2.0-l.^2.*sin(theta1).*sin(theta2).*2.0)).*(l0.*cos(theta2)+l.*cos(theta1).*sin(theta2)-l.*cos(theta2).*sin(theta1)).*1.0./sqrt(l.^2.*cos(theta1).^2+l.^2.*cos(theta2).^2+l.^2.*sin(theta1).^2+l.^2.*sin(theta2).^2+l0.^2-l.*l0.*sin(theta1).*2.0+l.*l0.*sin(theta2).*2.0-l.^2.*cos(theta1).*cos(theta2).*2.0-l.^2.*sin(theta1).*sin(theta2).*2.0))./(l.*m)];
qdd = [mt1;mt2];
end
