function M = Mass_matrix(l,m)
%Mass_matrix
%    M = Mass_matrix(L,m)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    30-Jul-2025 11:11:05

M = reshape([l.^2.*m,0.0,0.0,l.^2.*m],[2,2]);
end
