function K = Stiffness_matrix(k,l)
%Stiffness_matrix
%    K = Stiffness_matrix(k,L)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    30-Jul-2025 11:11:05

K = reshape([k.*l.^2,-k.*l.^2,-k.*l.^2,k.*l.^2],[2,2]);
end
